---
description: 'Дополнительные сведения: "GoTo <labelname> " является недопустимым, так как " <labelname> " находится внутри оператора "try", "Catch" или "finally", не содержащего этот оператор'
title: Оператор "GoTo <labelname>" является недопустимым, так как "<labelname>" находится в теле оператора "Try", "Catch" или "Finally", не содержащего этот оператор
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 952612fbac2304f57cf2d0a7ac6e701f1d5bb054
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100437414"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>Оператор "GoTo \<labelname>" является недопустимым, так как "\<labelname>" находится в теле оператора "Try", "Catch" или "Finally", не содержащего этот оператор

Нельзя осуществлять ветвление в блок `Try...Catch...Finally` .  
  
 **Идентификатор ошибки:** BC30754  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
- Перестройте ваш код, чтобы метка располагалась перед блоком `Try...Catch...Finally` .  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
