---
description: 'Дополнительные сведения о: блок "Catch" никогда не достигается; <exception> обрабатывается выше в одном операторе "try"'
title: Невозможно достичь блок "Catch"; "<exception>" обрабатывается выше в том же операторе Try
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: fc52c21f7a319c26b6ca7128c8d2d781db1a58c1
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473025"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Невозможно достичь блок "Catch"; "\<exception>" обрабатывается выше в том же операторе Try

Блок `Catch` в коде недоступен, так как он обрабатывается в предыдущем блоке `Try` .  
  
По умолчанию данное сообщение является предупреждением. Дополнительные сведения о сокрытии предупреждений и обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Идентификатор ошибки:** BC42031  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
- Удалите лишний оператор.  
  
## <a name="see-also"></a>См. также раздел

- [Использование блока try/catch для перехвата исключений](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Использование обработчиков исключений с пользовательской фильтрацией](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
